### ISSUE TITLE
Cambios software de reserva Sisgrae 

### ISSUE THREAD

**Issue by leoramz** [terrill021/sisgrae#2]
1. Cambiar logo 
2. Cambiar nombre (Cieducar) 
3. Revisar ortografía de todo el contenido de software (Mayúsculas  y tildes)
4. No permitir que el software realice reservas con fechas anteriores 
5. Se sobreponen los títulos 
6. Mostrar el numero de reservaciones que tiene el usuario pendientes por usar en el software 
7. Todas las notificaciones deben llegar al correo del usuario (Reservadas y Canceladas)
8.  Habilitar el Botón de cancelar al momento de confirmar la reservacion (Que regrese al segundo paso de la reserva) 
9. Centrar el calendario 
10. El link del reglamento está roto
11. El link del cambio de clave está roto

**Comment by terrill021** [comment]
El requerimiento:
 7. Todas las notificaciones deben llegar al correo del usuario (Reservadas y Canceladas)

Fue movido a un nuevo repositorio, el que corresponde a la aplicación backend de SISGRAE.

**Comment by terrill021** [comment]
Las observaciones fueron revisadas y corregidas según los requerimientos pasados.
[cambiossSISGRAE.docx](https://github.com/terrill021/sisgrae/files/978939/cambiossSISGRAE.docx)

**Comment by leoramz** [comment]
Buen dia,

1. El usuario debe solicitar las salas mínimo con 3 días de anticipación.
